- 'name': 'Radio 357'
  'url': 'https://stream.rcs.revma.com/an1ugyygzk8uv'
- 'name': 'Nowy Swiat'
  'url': 'https://stream.nowyswiat.online/mp3'
- 'name': 'Polskie Radio 1'
  'url': 'http://stream3.polskieradio.pl:8904/;'
